---
app_name: image-generation-server
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
kubeconfig: /home/ubuntu/.kube/config
firebase_bucket: friendlyeats-7fa2f.appspot.com
firebase_folder: test-images