// <auto-generated />
using ImageGenerationServer.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImageGenerationServer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230609172837_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("ImageGenerationServer.DTO.PendingVerifyPhrase", b =>
                {
                    b.Property<string>("Phrase")
                        .HasColumnType("TEXT");

                    b.HasKey("Phrase");

                    b.ToTable("PendingVerifyPhrases");
                });
#pragma warning restore 612, 618
        }
    }
}
