---
- name: check server is responding
  uri:
    url: "https://{{ inventory_hostname }}/{{ namespace }}/healthz"
    return_content: yes
    status_code: 200
    body_format: json
  register: result
  until: result.status == 200
  retries: 20
  delay: 30
  tags: verify
- name: check rest response
  fail:
    msg: "{{ result }}"
  when: result.json[0] is not defined
